### ISSUE TITLE
Copy of SecondBase not Properly Licensed

### ISSUE THREAD

**Issue by metaskills** [jomei/multibase#1]
Thanks so much for posting your solution to the SecondBase issue (https://github.com/customink/secondbase/issues/41) where a Third database option was requested. You appear to have copied SecondBase and re-published in a way that does not give credit to our MIT license and original authorship. For example:

https://github.com/customink/secondbase/blob/master/lib/second_base/databases.rake
https://github.com/jomei/multibase/blob/master/lib/multibase/tasks/database.rake

I am certain you did not intend to mis-credit our work. Would you mind correcting this and updating your LICENSE to include our original copyright as stated by the MIT? It would be nice too if you mentioned in your README where most of this code and inspiration came from. Thanks in advance!

cc @karledurante 
cc @hmadison

**Comment by jomei** [comment]
@metaskills, I updated README and LICENCE [here](https://github.com/jomei/multibase/commit/f52e7680adf75e2a60e1c79dadc4839c25d26706)
Is it correct or I should fix something else?

**Comment by metaskills** [comment]
Wow! That looks great. Really appreciate it. I'll close this issue too.
